default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: patreewi_novog58
  username: patreewi_novog58
  password: dmRXDf9Ktr
  host: mysql7.locum.ru
