default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: patreewi_novog25
  username: patreewi_novog25
  password: 6ZI0OAtMqH
  host: mysql7.locum.ru
